In [ ]:
"""Reproduce ENCODE/EpiATLAS 10% cell type overlap error that was present in preprint v1.
"""
# pylint: disable=import-error, redefined-outer-name, too-many-lines
from pathlib import Path

import pandas as pd
from IPython.display import display

from epiclass.utils.notebooks.paper.paper_utilities import ASSAY, CELL_TYPE

Recovers how the ~10% "biospecimen overlap" number in preprint v1 was produced.

The v1 figure was **not** a general biospecimen-source overlap. It was the fraction of ENCODE samples whose cell type falls into one of the **16 cell-type classes used by the Biospecimen classifier**: a narrower definition later misread as overall overlap and generalized to the other classifiers.

Details that are load-bearing and explain why later attempts landed at different values instead:
- the **old metadata snapshot** (`..._2023-10-25_clean-v2.csv`), not a current version;
  - this version contained some errors pointed out in [encode_metadata_creation.ipynb](https://github.com/labjacquespe/EpiClass/blob/e87306bccecd3e35d9ffdbb5ddb29fcaa0800a35/src/python/epiclass/utils/notebooks/paper/encode_metadata_creation.ipynb), which re-created the metadata from scratch
  - this version did not include RNA-Seq or WGBS data

In [ ]:
EPIATLAS_16_CT = [
    ct.lower()
    for ct in [
        "T cell",
        "neutrophil",
        "brain",
        "monocyte",
        "lymphocyte of B lineage",
        "myeloid cell",
        "venous blood",
        "macrophage",
        "mesoderm-derived structure",
        "endoderm-derived structure",
        "colon",
        "connective tissue cell",
        "hepatocyte",
        "mammary gland epithelial cell",
        "muscle organ",
        "extraembryonic cell",
    ]
]

In [21]:
encode_metadata_dir = (
    Path.home() / "Projects/epiclass/output/paper/data/metadata/encode/old_meta"
)

In [39]:
meta_df = pd.read_csv(
    encode_metadata_dir / "encode_metadata_2023-10-25_clean-v2.csv", low_memory=False
)
print(meta_df.shape)
display(meta_df.head())

(9619, 183)

,md5sum,File format,File type,Output type,File assembly,Assay,Donor(s),Biosample term id,Biosample term name_x,Biosample organism,...,biosample_treatment_duration,biosample_treatment_duration_units,biosample_modification_site_target_organism,biosample_modification_site_introduced_gene_organism,replicates,cellular_component,files_replace,donor_sex,cancer_status,experiment_accession
0,ENCFF072UFE,bigWig,bigWig,signal p-value,GRCh38,H3K4me2,/human-donors/ENCDO000AAZ/,EFO:0001086,A549,Homo sapiens,...,unknown,unknown,unknown,unknown,unknown,unknown,unknown,male,cancer,ENCSR918VQU
1,ENCFF114UFW,bigWig,bigWig,signal p-value,GRCh38,KDM5A,/human-donors/ENCDO000AAZ/,EFO:0001086,A549,Homo sapiens,...,unknown,unknown,unknown,unknown,unknown,unknown,unknown,male,cancer,ENCSR933MHJ
2,ENCFF604SWJ,bigWig,bigWig,signal p-value,GRCh38,H3K4me3,/human-donors/ENCDO000AAB/,EFO:0002791,HeLa-S3,Homo sapiens,...,unknown,unknown,unknown,unknown,unknown,unknown,unknown,female,cancer,ENCSR000AOF
3,ENCFF562UDF,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,unknown,...,48,hour,unknown,unknown,/replicates/7cdba585-65b5-439c-bb03-463c8ae8da40/,unknown,"ENCFF044QFZ,ENCFF562UDF,ENCFF778HQR,ENCFF954SAX",unknown,unknown,ENCSR086GBI
4,ENCFF654CFQ,bigWig,bigWig,signal p-value,GRCh38,H3K27ac,/human-donors/ENCDO640RUC/,UBERON:0006483,middle frontal area 46,Homo sapiens,...,unknown,unknown,unknown,unknown,unknown,unknown,unknown,female,non-cancer,ENCSR004YQD

In [23]:
for column in meta_df.columns:
    print(column)

md5sum
File format
File type
Output type
File assembly
Assay
Donor(s)
Biosample term id
Biosample term name_x
Biosample organism
Biosample treatments
Biosample treatments amount
Biosample treatments duration
Biosample genetic modifications methods
Biosample genetic modifications categories
Biosample genetic modifications targets
Biosample genetic modifications gene targets
Biosample genetic modifications site coordinates
Biosample genetic modifications zygosity
Experiment target
Library made from
Library lysis method
Library crosslinking method
Experiment date released
Library fragmentation method
Library size range
Biological replicate(s)
Technical replicate(s)
Derived from
Size
Lab_x
md5sum_encode
File download URL
File Status
s3_uri
Azure URL
File analysis title
File analysis status
Audit WARNING
Audit NOT_COMPLIANT
Audit ERROR
assay_epiclass
track_type
uuid
ID
Assay name
Assay title
Target
Target of assay
Target gene symbol
biosample_summary
Biosample term name_y
Dbxrefs
Description
Lab_y
Status
Files
Related series
Biosample accession
Biological replicate
Technical replicate
Linked antibody
Organism
life_stage
biosample_age
Biosample treatment
Biosample treatment ontology ID
Biosample treatment amount
Biosample treatment amount units
Biosample treatment duration
Biosample treatment duration units
Biosample modification site target organism
Biosample modification site introduced gene organism
Replicates
Cellular component
Files_replace
Submitter comment
Biosample ontology
Documents
References
Schema version
Alternate accessions
Analysis objects
Date released
Digital object identifier
Internal tags
Notes
Date created
Submitted by
Award
Aliases
UUID
Date submitted
Controls
Supersedes
Internal status
Pipeline error message
Biological replicate count
Technical replicate count
Replication type
Assay type
Simple biosample_summary
Assay term ID
Type
Original files
Contributing files
Revoked files
Genome assembly
Hub
Default analysis
Related annotations
Protein tags
life_stage and age summary
Perturbed
file_format
file_type
output_type
file_assembly
assay
donors
biosample_term_id
biosample_term_name_x
biosample_type
biosample_organism
biosample_treatments
biosample_treatments_amount
biosample_treatments_duration
biosample_genetic_modifications_methods
biosample_genetic_modifications_categories
biosample_genetic_modifications_targets
biosample_genetic_modifications_gene_targets
biosample_genetic_modifications_site_coordinates
biosample_genetic_modifications_zygosity
library_made_from
library_lysis_method
library_crosslinking_method
experiment_date_released
project_x
library_fragmentation_method
library_size_range
biological_replicates
technical_replicates
mapped_read_length
derived_from
size
lab_x
file_download_url
file_status
azure_url
file_analysis_title
file_analysis_status
audit_warning
audit_not_compliant
audit_error
id
assay_name
assay_title
biosample_term_name_y
dbxrefs_y
description
lab_y
status
files
related_series
biosample_accession
biological_replicate
technical_replicate
linked_antibody
organism
biosample_treatment
biosample_treatment_ontology_id
biosample_treatment_amount
biosample_treatment_amount_units
biosample_treatment_duration
biosample_treatment_duration_units
biosample_modification_site_target_organism
biosample_modification_site_introduced_gene_organism
replicates
cellular_component
files_replace
donor_sex
cancer_status
experiment_accession

Drop ENCODE entries linked to IHEC reference epigenomes, so the comparison is against independent samples.

In [24]:
# exclude epiatlas overlap
meta_df = meta_df[~meta_df["Related series"].str.contains("reference-epigenomes")]
print(meta_df.shape)

(7283, 183)

Attach harmonized cell-type annotations

Map each `biosample_term_id` to its harmonized ontology intermediate term via the EpiATLAS CURIE table, so ENCODE samples can be checked against the classifier's classes.

In [ ]:
curie_def_df = pd.read_csv(
    encode_metadata_dir / "EpiAtlas_list-curie_term_HSOI.tsv",
    sep="\t",
    names=["biosample_term_id", "biosample_term_name", CELL_TYPE],
)
display(curie_def_df.head())

,biosample_term_id,biosample_term_name,harmonized_sample_ontology_intermediate
0,CL:0000019,sperm,germ line cell
1,CL:0000037,hematopoietic stem cell,hematopoietic cell
2,CL:0000038,erythroid progenitor cell,hematopoietic cell
3,CL:0000041,mature eosinophil,eosinophil
4,CL:0000047,neural stem cell,neural cell

In [ ]:
new_df = pd.merge(
    left=meta_df,
    right=curie_def_df[["biosample_term_id", CELL_TYPE]],
    on="biosample_term_id",
    how="left",
)
print(new_df.shape)

(7283, 184)

In [38]:
# Uniformize labels
new_df[CELL_TYPE] = new_df[CELL_TYPE].str.lower()

## The error mechanism: restricting "overlap" to the 16 classifier classes

`EPIATLAS_16_CT` is the set of harmonized intermediate cell-type classes the Biospecimen classifier predicts, **not** the full set of EpiATLAS ontology terms. Defining overlap as "sample's cell type ∈ these 16 classes" answers a different question than "sample shares an ontology term with any EpiATLAS sample":

- it collapses to 16 coarse classes instead of the full term set, and
- a sample sharing a term *outside* the 16 counts as non-overlapping here.

This is the definition that yields ~10%; treating it as general biospecimen overlap is
the error corrected in the revision.

In [30]:
new_df[ASSAY].value_counts(dropna=False)

assay_epiclass
non-core    3200
input       1981
h3k4me3      380
h3k27ac      367
CTCF         309
h3k27me3     296
h3k4me1      260
h3k36me3     247
h3k9me3      243
Name: count, dtype: int64

In [ ]:
core_df = new_df[~new_df[ASSAY].isin(["non-core", "CTCF"])]
print(core_df[ASSAY].value_counts(dropna=False))

N = core_df[CELL_TYPE].isin(EPIATLAS_16_CT).sum()
print(N, core_df.shape[0], f"{N/len(core_df):.1%}")

assay_epiclass
input       1981
h3k4me3      380
h3k27ac      367
h3k27me3     296
h3k4me1      260
h3k36me3     247
h3k9me3      243
Name: count, dtype: int64
388 3774 10.3%